services:
  fastapi:
    build: .
    image: theankitdash/nutrify-health:latest
    container_name: nutrify-health
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env


  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data    
volumes:
  pgdata: